import { Component, OnInit } from '@angular/core';
import { SimpleCube } from '../../libs/SimpleCube';

@Component({
  selector: 'app-cube-solver',
  templateUrl: './cube-solver.component.html',
  styleUrls: ['./cube-solver.component.scss']
})
export class CubeSolverComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    var component = new SimpleCube();
    component.start();
    var duration = 200;
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)
    component.doRotateAPI('F', 90, duration)
    component.doRotateAPI('R', -90, duration)




  }

}
